name: Push (build and unit test)

on:
  push: {}
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  clj-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Install Clojure and Tools
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          lein: 'latest'               # Leiningen
          bb: 'latest'
      - name: Cache Clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
          # List all files containing dependencies:
          key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
          restore-keys: cljdeps-

      - name: Run lein test
        run: lein test

  cljs-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile cljs
        run: npx shadow-cljs compile test
      - name: Run npm tests
        run: node build/test.js

  dctest-compose-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: npm install dctest
        run: npm install @lonocloud/dctest --no-save --ignore-scripts

      - name: compose build (dhcp,ping,mac2ip profiles)
        run: docker compose --profile dhcp --profile ping --profile mac2ip build

      - name: run dctest tests
        run: time node_modules/.bin/dctest --verbose-commands clj-protocol-test test/basics.yaml
