name: Push (build and unit test)

on:
  push: {}
  pull_request:
    branches: [ master ]
  workflow_dispatch: {}

jobs:
  lsmod:
    runs-on: ubuntu-latest
    steps:
      - name: show lsmod
        run: lsmod
      - name: test docker privileged
        run: |
          docker run --privileged --rm ubuntu:latest id
